### ISSUE TITLE
能否提供DockerFile

### ISSUE THREAD

**Issue by cgcgbcbc** [medcl/elasticsearch-rtf#18]
如题...能否提供DockerFile更加方便使用

**Comment by i6448038** [comment]
跪求elasticsearch-rft 的docker镜像，自己安装plugin太麻烦了

**Comment by cdyue** [comment]
EagleChen做了一个..
https://github.com/EagleChen/docker_elasticsearch_rtf

我在他的基础上修改了一个,
1.解决了container外无法访问的问题.
2.去掉了gosu
3.默认启用mmseg分词.

地址https://github.com/cdyue/docker-elasticsearch-rtf

**Comment by i6448038** [comment]
我做了一个：
https://github.com/i6448038/elasticsearch-rtf

**Comment by medcl** [comment]
https://github.com/elastic/elasticsearch-docker/blob/master/README.md
