### ISSUE TITLE
为什么总是不能设置默认分词

### ISSUE THREAD

**Issue by kevinxinfeng** [medcl/elasticsearch-rtf#34]
PUT /index/
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "default": {
            "type": "ik"
          }
        }
      }
    }
  }
}

总是返回 
{
   "error": {
      "root_cause": [
         {
            "type": "index_creation_exception",
            "reason": "failed to create index"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Unknown Analyzer type [ik] for [default]"
   },
   "status": 400
}

**Comment by cdyue** [comment]
试试看修改config中的elasticsearch.yml,把
```
#index.analysis.analyzer.default.type: mmseg
index.analysis.analyzer.default.type: keyword
```
修改为
```
index.analysis.analyzer.default.type: mmseg
#index.analysis.analyzer.default.type: keyword
```
然后重启elasticsearch试试.
