### ISSUE TITLE
能否请为版本 2.2, 2.2.1 加上 tag 并且 release?

### ISSUE THREAD

**Issue by chuangbo** [medcl/elasticsearch-rtf#36]
能否请为版本 2.2, 2.2.1 加上 tag 并且 release？
这样方便我们加到 Dockerfile 里，去下载特定版本的包，而不是从 master 下载，造成未知的错误。

谢谢了

**Comment by medcl** [comment]
2.2没有加，只有2.2.1，可以么？

**Comment by chuangbo** [comment]
看到了，谢谢
