### ISSUE TITLE
有集成中文分词吗？

### ISSUE THREAD

**Issue by Petelin** [medcl/elasticsearch-rtf#45]
我没看到有传说中的ik，试着match 全文搜索 "卡”找不到， “学生卡"能找到，是不是没有没有分词的原因？。

**Comment by lanhaoxiang** [comment]
@Petelin 借鉴作者思路我弄了个带ik的 [elasticsearch-2.3.3-rtf](https://github.com/lanhaoxiang/elasticsearch-2.3.3-rtf) ，不过和作者比起来还是小巫见大巫了

**Comment by Steven-Z-Yang** [comment]
当然有分词功能了，里面就集成有ik，mmsg等
